name: Deploy CALC Natively

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Execute remote SSH deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            if [ ! -d "~/CALC" ]; then
              git clone git@github.com:caioronaldsilva/CALC.git ~/CALC
            fi
            
            cd ~/CALC
            git pull origin main
            
            npm install --production
            
            pm2 restart calc-app || pm2 start server.js --name "calc-app"